<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.0.0-rc5" />
    <PackageReference Include="Jellyfin.Model" Version="12.0.0-rc5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\*.html" />
    <EmbeddedResource Include="Configuration\*.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="build\**" />
  </ItemGroup>

</Project>
